[package]
name = "ch4_ownership"
version = "0.1.0"
authors = ["ahmadmijot <ahmad.mijot@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
